### ISSUE TITLE
Fix Render deploys

### ISSUE THREAD

**Issue by ColeDCrawford** [dh-tech/dh-tech.github.io#81]

**Comment by ColeDCrawford** [comment]
Render PR build seems broken to me - no styles, and if you click on a post it 404s because it's trying to go to dh-tech.onrender.com instead of dh-tech-pr-##.onrender.com.

Example: https://dh-tech.onrender.com/2023/09/28/DHTech-October-Meetup/ instead of https://dh-tech-pr-87.onrender.com/2023/09/28/DHTech-October-Meetup/

**Comment by rlskoeser** [comment]
Aware since the first time Julia opened a PR on the new site but haven't had time to investigate. I just set a `HUGO_ENV` of `staging` in the render build environment, I use that on some of my other builds but IDK if it's sufficient (when env is production it uses the official url in the site config). Is there an easy way to test to see if this config change is enough?
